# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 19:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[(b'premium', b'premium'), (b'trial', b'trial'), (b'vip', b'vip'), (b'user', b'user'), (b'enterprise', b'enterprise'), (b'user_inactive', b'user_inactive')], max_length=100)),
                ('child', models.CharField(blank=True, max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='role', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
